# Generated by Django 5.0.2 on 2024-08-14 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Security', '0002_staffauthtokens_delete_administratorauthtokens_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminAuthTokens',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('access_token', models.TextField(db_column='auth_access_token', null=True)),
                ('refresh_token', models.TextField(db_column='auth_refresh_token', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'hm_admin_auth_tokens',
            },
        ),
    ]
