# Generated by Django 5.0.2 on 2024-08-20 06:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Customer', '0001_initial'),
        ('OrderFood', '0002_foodmenu_is_available'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderedFood',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('orderedfood_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Customer.customers')),
                ('food', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='OrderFood.foodmenu')),
            ],
            options={
                'db_table': 'hm_orderedfood',
            },
        ),
    ]
