# Generated by Django 5.0.2 on 2024-08-15 20:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Customer', '0001_initial'),
        ('RoomBooking', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rooms',
            name='date_from',
        ),
        migrations.RemoveField(
            model_name='rooms',
            name='date_to',
        ),
        migrations.RemoveField(
            model_name='rooms',
            name='is_available',
        ),
        migrations.CreateModel(
            name='BookedRooms',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('BookedRoom_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('date_from', models.DateField()),
                ('date_to', models.DateField()),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Customer.customers')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='RoomBooking.rooms')),
            ],
            options={
                'db_table': 'hm_bookedrooms',
            },
        ),
    ]
