# Generated by Django 5.0.2 on 2024-08-19 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Inventory', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventory',
            name='is_roominventory',
            field=models.BooleanField(default=False),
        ),
    ]
