# Generated by Django 5.0.2 on 2024-08-14 04:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Staff', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='staff',
            old_name='customer_id',
            new_name='staff_id',
        ),
    ]
